#!/usr/bin/env python3
"""Collect every exercise's DEBUG-LOG.md and AI-DELTA.md into logs/INDEX.md.

Entries are the level-2 headings in those files. This is deliberately simple: it
reads headings, it does not parse prose. The generated file is a table of
contents, not a substitute for reading the logs.
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
EXERCISES = REPO / "exercises"
OUT = REPO / "logs" / "INDEX.md"

HEADING = re.compile(r"^##\s+(.*?)\s*$", re.MULTILINE)


def headings(path: Path):
    if not path.is_file():
        return []
    return HEADING.findall(path.read_text(encoding="utf-8"))


def main() -> int:
    if not EXERCISES.is_dir():
        print("No exercises directory, nothing to index.")
        return 0

    lines = [
        "# Log index",
        "",
        "Generated by `tools/index_logs.py`. Do not edit by hand; your changes",
        "will be overwritten on the next run. Edit the per-exercise logs instead.",
        "",
    ]

    debug_total = 0
    delta_total = 0

    for exercise in sorted(p for p in EXERCISES.iterdir() if p.is_dir()):
        debug = headings(exercise / "DEBUG-LOG.md")
        delta = headings(exercise / "AI-DELTA.md")
        if not debug and not delta:
            continue

        debug_total += len(debug)
        delta_total += len(delta)

        lines.append(f"## {exercise.name}")
        lines.append("")

        if debug:
            rel = f"../exercises/{exercise.name}/DEBUG-LOG.md"
            lines.append(f"Debug entries ([log]({rel})):")
            lines.append("")
            lines.extend(f"- {h}" for h in debug)
            lines.append("")

        if delta:
            rel = f"../exercises/{exercise.name}/AI-DELTA.md"
            lines.append(f"AI delta entries ([log]({rel})):")
            lines.append("")
            lines.extend(f"- {h}" for h in delta)
            lines.append("")

    lines.append(
        f"Totals: {debug_total} debug entries, {delta_total} AI delta entries."
    )
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}: {debug_total} debug, {delta_total} delta")
    return 0


if __name__ == "__main__":
    sys.exit(main())
